04-lab/agency/urls.py
from django.urls import path, include
from .views import home, destination_list, hotel_list, package_list, package_detail, signup, create_package, delete_package, update_package, create_order, order_list, about_us, order_detail
from django.contrib.auth import views as auth_views
from .forms import LoginForm


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('about_us', about_us, name='about_us'),
    path('destinations/', destination_list, name='destination_list'),
    path('hotels/', hotel_list, name='hotel_list'),
    path('packages/', package_list, name='package_list'),
    path('orders/', order_list, name='order_list'),
    path('orders/<int:order_id>/', order_detail, name='order_detail'),
    path('packages/package/<int:package_id>/', package_detail, name='package_detail'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('signup/', signup, name='signup'),
    path('packages/create/', create_package, name='create_package'),
    path('packages/delete/<int:package_id>/', delete_package, name='delete_package'),
    path('packages/update/<int:package_id>/', update_package, name='update_package'),
    path('packages/<int:package_id>/create_order/', create_order, name='create_order')
]

04-lab/travel_agency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('agency.urls')),
    
]

04-lab/agency/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser, Group, Permission

class Climate(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50)
    climates = models.ManyToManyField(Climate, related_name='countries')

    def __str__(self):
        return self.name


class Hotel(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='hotels')
    star_rating = models.IntegerField(default=0)
    price_per_night = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return self.name


class Client(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.TextField(default="no address")
    phone = models.CharField(max_length=20, default='')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    

class Employee(AbstractUser):
    groups = models.ManyToManyField(Group, blank=True, related_name='employee_groups')
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name='employee_user_permissions')



class Package(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    hotels = models.ManyToManyField(Hotel)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    duration = models.PositiveIntegerField(default=0)
    created_by = models.ForeignKey(Employee, on_delete=models.CASCADE, null=True, related_name='created_packages')

    def __str__(self):
        return self.name


class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='orders')
    package = models.ForeignKey(Package, on_delete=models.CASCADE, null=True)
    order_date = models.DateField(default=datetime.now)

    def __str__(self):
        return f'Order for {self.client}'

04-lab/agency/forms.py
from django import forms
from .models import Client, Package, Order
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import EmailValidator, RegexValidator



class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
    }))


class PackageForm(forms.ModelForm):
    class Meta:
        model = Package
        fields = ('name', 'country', 'hotels', 'price', 'duration')

    price = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={}))        


class ClientForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={}), validators=[EmailValidator()])
    phone = forms.CharField(widget=forms.TextInput(attrs={}), validators=[RegexValidator(r'^\+?1?\d{9,15}$', 'Enter a valid phone number.')])

    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'address', 'phone']

04-lab/agency/views.py
from django.shortcuts import render, redirect
from .models import Client, Order, Package, Country, Hotel
from .forms import LoginForm, SignupForm, PackageForm, ClientForm
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import authenticate
import requests

# Create your views here.


def home(request):
    return render(request, 'home.html')

def about_us(request):
    response = requests.get('https://api.chucknorris.io/jokes/random').json()
    context = {'response': response}
    return render(request, 'about_us.html', context)

#view 
def destination_list(request):
    countries = Country.objects.all()
    return render(request, 'destination_list.html', {'countries': countries})

def hotel_list(request):
    hotels = Hotel.objects.all()
    return render(request, 'hotel_list.html', {'hotels': hotels})

def package_list(request):
    packages = Package.objects.all()
    return render(request, 'package_list.html', {'packages': packages})

def order_list(request):
    orders = Order.objects.all()
    context = {'orders': orders}
    return render(request, 'order_list.html', context)

#detail
def package_detail(request, package_id):
    package = Package.objects.get(pk=package_id)
    return render(request, 'package_detail.html', {'package': package})

#signup
def signup(request):
    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = SignupForm()

    context = {'form': form}
    return render(request, 'registration/signup.html', context,)

#crud operations
def create_package(request):
    if request.method == 'POST':
        form = PackageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = PackageForm()
    
    context = {'form': form}
    return render(request, 'create_package.html', context)

def update_package(request, package_id):
    package = Package.objects.get(id=package_id)
    countries = Country.objects.all()
    hotels = Hotel.objects.all()
    if request.method == 'POST':
        form = PackageForm(request.POST, instance=package)
        if form.is_valid():
            form.save()
            return redirect('package_detail', package_id=package_id)
    else:
        form = PackageForm(instance=package)

    context = {'form': form, 'package': package, 'countries': countries, 'hotels': hotels}
    return render(request, 'update_package.html', context)

def delete_package(request, package_id):
    package = Package.objects.get(id=package_id)
    if request.method == 'POST':
        package.delete()
        return redirect('home')

    return redirect('package_list')

#order
def create_order(request, package_id):
    package = Package.objects.get(id=package_id)

    if request.method == 'POST':
        client_form = ClientForm(request.POST)
        if client_form.is_valid():
            client = client_form.save()
            order = Order.objects.create(client=client, package=package)
            return redirect('package_detail', package_id=package_id)
    else:
        client_form = ClientForm()

    context = {'client_form': client_form, 'package': package}
    return render(request, 'create_order.html', context)

def order_detail(request, order_id):
    order = Order.objects.get(id=order_id)
    context = {'order': order}
    return render(request, 'order_detail.html', context)

04-lab/agency/templates/about_us.html
{% extends 'base.html' %}

{% block content %}
    <h1>
        {{response.value}}
    </h1>
    
{% endblock %}

04-lab/agency/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>User authenticate</title>
</head>
<body class="container">
<ul class="list-group">
    <li class="list-group-item">
        User: {{ user }}
    </li>
    <li class="list-group-item">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'about_us' %}">About Us</a>
    </li>
</ul>

{% block content %}
{% endblock %}

</body>
</html>

04-lab/agency/templates/create_order.html
{% extends 'base.html' %}

{% block content %}
  <h1>Add Order</h1>
  <h2>Package Details</h2>
  <p>Name: {{ package.name }}</p>
  <p>Country: {{ package.country }}</p>
  <p>Price: {{ package.price }}</p>
  <p>Duration: {{ package.duration }}</p>
  <h2>Hotels</h2>
  <ul>
    {% for hotel in package.hotels.all %}
      <li>{{ hotel.name }} - {{ hotel.country }} - {{ hotel.star_rating }} stars - Price per night: {{ hotel.price_per_night }}</li>
    {% endfor %}
  </ul>
  <form method="post">
    {% csrf_token %}
    {{ client_form.as_p }}
    <button type="submit">Create Order</button>
  </form>
{% endblock %}

04-lab/agency/templates/create_package.html
{% extends 'base.html' %}

{% block content %}
  <h1>Create Package</h1>
  <hr>

  <form action="{% url 'create_package' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Create</button>
  </form>
{% endblock %}

04-lab/agency/templates/destination_list.html
{% extends 'base.html' %}

{% block content %}
<form>
    <h1>Destinations</h1>
    <ul>
        {% for country in countries %}
            <li>{{ country.name }}</li>
        {% endfor %}
    </ul>
</form>
    
{% endblock %}

04-lab/agency/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Home page</h1>

    <h1>Welcome to the Travel Agency!</h1>
    <ul>
        <li><a href="{% url 'destination_list' %}">Destinations</a></li>
        <li><a href="{% url 'hotel_list' %}">Hotels</a></li>
        <li><a href="{% url 'package_list' %}">Packages</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'order_list' %}">Orders</a></li>
        {% else %}
        {% endif %}
    </ul >

    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a> |
        <a href="{% url 'signup' %}">Register</a>
    {% endif %}
{% endblock %}

04-lab/agency/templates/hotel_list.html
{% extends 'base.html' %}

{% block content %}
<form>
    <h1>Hotels</h1>
    <ul>
        {% for hotel in hotels %}
            <li>{{ hotel.name }} - Rating: {{ hotel.star_rating }} - Price per night: {{ hotel.price_per_night }}</li>
        {% endfor %}
    </ul>
</form>
    
{% endblock %}

04-lab/agency/templates/order_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Order Detail</h1>
  <h2>Order ID: {{ order.id }}</h2>
  <p>Client: {{ order.client }}</p>
  <p>Package: {{ order.package }}</p>
  <p>Order Date: {{ order.order_date }}</p>
{% endblock %}

04-lab/agency/templates/order_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Order List</h1>
  <ul>
    {% for order in orders %}
      <li><a href="{% url 'order_detail' order.id %}">{{ order.client.first_name }} {{ order.client.last_name }} - {{ order.package.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

04-lab/agency/templates/package_detail.html
{% extends 'base.html' %}

{% block content %}
<form>
    <h1>{{ package.name }}</h1>
    <p>Country: {{ package.country.name }}</p>
    <p>Duration: {{ package.duration }} days</p>
    <p>Price: {{ package.price }}</p>
    <p>Hotels:</p>
    <ul>
        {% for hotel in package.hotels.all %}
        <li>{{ hotel.name }} - {{ hotel.star_rating }} stars - Price per night: {{ hotel.price_per_night }}</li>
        {% endfor %}
    </ul>
</form>
    
    {% if user.is_authenticated %}
    <form action="{% url 'update_package' package_id=package.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Update Package</button>
      </form>
    <form action="{% url 'delete_package' package_id=package.id %}" method="post">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('Are you sure you want to delete this package?')">Delete Package</button>
    </form>
        
    {% else %}
    <form action="{% url 'create_order' package_id=package.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Make Order</button>
    </form>
    {% endif %}

{% endblock %}

04-lab/agency/templates/package_list.html
{% extends 'base.html' %}

{% block content %}
<form>
    <h1>Packages</h1>
    <ul>
        {% for package in packages %}
        <li><a href="{% url 'package_detail' package.id %}">{{ package.name }}</a></li>
        {% endfor %}
    </ul>
</form>
    
    {% if user.is_authenticated %}
        <a href="{% url 'create_package' %}">Add Package</a>
    {% else %}
    {% endif %}

{% endblock %}

04-lab/agency/templates/update_package.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Package</h1>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="id_name">Name:</label>
            <input type="text" name="name" id="id_name" value="{{ package.name }}">
        </div>
        <div>
            <label for="id_country">Country:</label>
            <select name="country" id="id_country">
                {% for country in countries %}
                    <option value="{{ country.id }}" {% if country.id == package.country.id %}selected{% endif %}>{{ country.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="id_hotels">Hotels:</label>
            <select name="hotels" id="id_hotels" multiple>
                {% for hotel in hotels %}
                    <option value="{{ hotel.id }}" data-country="{{ hotel.country.id }}" {% if hotel in package.hotels.all %}selected{% endif %}>{{ hotel.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="id_price">Price:</label>
            <input type="text" name="price" id="id_price" value="{{ package.price }}">
        </div>
        <div>
            <label for="id_duration">Duration:</label>
            <input type="text" name="duration" id="id_duration" value="{{ package.duration }}">
        </div>
        <button type="submit">Update</button>
    </form>
{% endblock %}